CHANGELOG=improved selfup() operation flow

diff --git a/linkie b/linkie
--- a/linkie
+++ b/linkie
@@ -1,36 +1,14 @@
 #!/bin/sh -e
 
-case ${LANG} in
-  *eo*)
-    MSG_ERROR="[FATALA] eksportu CONFIG_DOTS_REPO al dotfile-a deponejo kaj reprovu."
-    MSG_PUSH="alŝuti dosierojn"
-    MSG_PUSH_FAIL="nenio por alŝuti"
-    MSG_RELINK="religado"
-    MSG_RELINK_FAIL="malsukcesis ĉe"
-    MSG_END="farita"
-    MSG_SELFUP_CURRENT="antaŭa binaro"
-    MSG_SELFUP_UPDATED="ĝisdatiganta binaro"
-    MSG_SELFUP_UP="ĝisdatiginta"
-  ;;
-  *)
-    MSG_ERROR="[FATAL] export CONFIG_DOTS_REPO to a dotfile repository and retry."
-    MSG_PUSH="pushing changes"
-    MSG_PUSH_FAIL="nothing to push"
-    MSG_RELINK="relinking"
-    MSG_RELINK_FAIL="failed at"
-    MSG_END="done"
-    MSG_SELFUP_CURRENT="current binary"
-    MSG_SELFUP_UPDATED="updated binary"
-    MSG_SELFUP_UP="updating"
-  ;;
-esac
-
-MSG_PUSH_GIT="<linkie> [`date -Is`]"
-
 BIN_PATH="/usr/bin"
+MSG_PUSH_GIT="<linkie> [`date -Is`]"
 CONFIG_PATH="${HOME}/.config"
 
-case ${CONFIG_DOTS_REPO} in "") echo ${MSG_ERROR}; exit 1 ;; esac
+CHANGELOG="improved selfup() operation flow"
+
+about() { ls -l ${BIN_PATH}/linkie; }
+
+case ${CONFIG_DOTS_REPO} in "") echo "export a CONFIG_DOTS_REPO and try again."; exit 1 ;; esac
 
 go() {
   cd ${CONFIG_DOTS_REPO}
@@ -38,7 +16,7 @@ go() {
   git add *
   git commit -m " ${MSG_PUSH_GIT}" && git push
 
-  printf "[linkie] ${MSG_RELINK}... "
+  printf "[linkie] linking... "
 
   for SYM in `find $PWD \
     -maxdepth 1 \
@@ -47,24 +25,19 @@ go() {
     -and -not -path "$PWD" | \
     sed "s|$PWD||g" | cut -c2-`; do
       ORIGIN="${CONFIG_DOTS_REPO}/${SYM}"; DEST="${CONFIG_PATH}/${SYM}"
-      rm -rf ${DEST} || true; ln -svf ${ORIGIN} ${DEST} || { echo "${MSG_RELINK_FAIL} ${ORIGIN}" && exit 1; }
+      rm -rf ${DEST} || true; ln -sf ${ORIGIN} ${DEST} || { echo "${MSG_RELINK_FAIL} ${ORIGIN}" && exit 1; }
   done
 
-  echo "${MSG_END}"
+  echo "done."
 }
 
-about() { ls -l ${BIN_PATH}/linkie; }
-
 selfup() {
-  if which sudo > /dev/null 2>&1; then SOUP=sudo;
-    else if which doas > /dev/null 2>&1; then SOUP=doas; else SOUP=""; fi fi
-  ls -l ${BIN_PATH}/linkie
-  ${SOUP} su -c "curl -sL https://github.com/draumaz/linkie/archive/refs/heads/main.tar.gz | \
-    tar -xpzf - \
+  about; curl -sL https://github.com/draumaz/linkie/archive/refs/heads/main.tar.gz | \
+    sudo tar -xpzf - \
       --strip-components=1 \
       -C ${BIN_PATH} \
-      linkie-main/linkie"
-  ls -l ${BIN_PATH}/linkie
+      linkie-main/linkie
+  about; printf "${CHANGELOG}"
 }
 
 case $1 in
