catched

diff --git a/linkie b/linkie
--- a/linkie
+++ b/linkie
@@ -10,7 +10,7 @@ printf "[linkie] relinking... "
 
 for SYM in `find $PWD -maxdepth 1 -not -name "*.git*" -and -not -path "$PWD" | sed "s|$PWD||g"`; do
   ORIGIN="${CONFIG_DOTS_REPO}/${SYM}"; DEST="${HOME}/.config/${SYM}"
-  rm -rf ${DEST} || true; ln -sf ${ORIGIN} ${DEST}
+  rm -rf ${DEST} || true; ln -sf ${ORIGIN} ${DEST} || { echo "failed at ${ORIGIN}" && exit 1; }
 done
 
 echo "done"
